# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pyocr', [dirname(__file__)])
        except ImportError:
            import _pyocr
            return _pyocr
        if fp is not None:
            try:
                _mod = imp.load_module('_pyocr', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _pyocr = swig_import_helper()
    del swig_import_helper
else:
    import _pyocr
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pyocr.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _pyocr.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _pyocr.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _pyocr.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _pyocr.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _pyocr.SwigPyIterator_equal(self, x)

    def copy(self):
        return _pyocr.SwigPyIterator_copy(self)

    def next(self):
        return _pyocr.SwigPyIterator_next(self)

    def __next__(self):
        return _pyocr.SwigPyIterator___next__(self)

    def previous(self):
        return _pyocr.SwigPyIterator_previous(self)

    def advance(self, n):
        return _pyocr.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _pyocr.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _pyocr.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _pyocr.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _pyocr.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _pyocr.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _pyocr.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _pyocr.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class FloatVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FloatVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FloatVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pyocr.FloatVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyocr.FloatVector___nonzero__(self)

    def __bool__(self):
        return _pyocr.FloatVector___bool__(self)

    def __len__(self):
        return _pyocr.FloatVector___len__(self)

    def __getslice__(self, i, j):
        return _pyocr.FloatVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyocr.FloatVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyocr.FloatVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyocr.FloatVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyocr.FloatVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyocr.FloatVector___setitem__(self, *args)

    def pop(self):
        return _pyocr.FloatVector_pop(self)

    def append(self, x):
        return _pyocr.FloatVector_append(self, x)

    def empty(self):
        return _pyocr.FloatVector_empty(self)

    def size(self):
        return _pyocr.FloatVector_size(self)

    def swap(self, v):
        return _pyocr.FloatVector_swap(self, v)

    def begin(self):
        return _pyocr.FloatVector_begin(self)

    def end(self):
        return _pyocr.FloatVector_end(self)

    def rbegin(self):
        return _pyocr.FloatVector_rbegin(self)

    def rend(self):
        return _pyocr.FloatVector_rend(self)

    def clear(self):
        return _pyocr.FloatVector_clear(self)

    def get_allocator(self):
        return _pyocr.FloatVector_get_allocator(self)

    def pop_back(self):
        return _pyocr.FloatVector_pop_back(self)

    def erase(self, *args):
        return _pyocr.FloatVector_erase(self, *args)

    def __init__(self, *args):
        this = _pyocr.new_FloatVector(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _pyocr.FloatVector_push_back(self, x)

    def front(self):
        return _pyocr.FloatVector_front(self)

    def back(self):
        return _pyocr.FloatVector_back(self)

    def assign(self, n, x):
        return _pyocr.FloatVector_assign(self, n, x)

    def resize(self, *args):
        return _pyocr.FloatVector_resize(self, *args)

    def insert(self, *args):
        return _pyocr.FloatVector_insert(self, *args)

    def reserve(self, n):
        return _pyocr.FloatVector_reserve(self, n)

    def capacity(self):
        return _pyocr.FloatVector_capacity(self)
    __swig_destroy__ = _pyocr.delete_FloatVector
    __del__ = lambda self: None
FloatVector_swigregister = _pyocr.FloatVector_swigregister
FloatVector_swigregister(FloatVector)

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pyocr.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyocr.StringVector___nonzero__(self)

    def __bool__(self):
        return _pyocr.StringVector___bool__(self)

    def __len__(self):
        return _pyocr.StringVector___len__(self)

    def __getslice__(self, i, j):
        return _pyocr.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyocr.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyocr.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyocr.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyocr.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyocr.StringVector___setitem__(self, *args)

    def pop(self):
        return _pyocr.StringVector_pop(self)

    def append(self, x):
        return _pyocr.StringVector_append(self, x)

    def empty(self):
        return _pyocr.StringVector_empty(self)

    def size(self):
        return _pyocr.StringVector_size(self)

    def swap(self, v):
        return _pyocr.StringVector_swap(self, v)

    def begin(self):
        return _pyocr.StringVector_begin(self)

    def end(self):
        return _pyocr.StringVector_end(self)

    def rbegin(self):
        return _pyocr.StringVector_rbegin(self)

    def rend(self):
        return _pyocr.StringVector_rend(self)

    def clear(self):
        return _pyocr.StringVector_clear(self)

    def get_allocator(self):
        return _pyocr.StringVector_get_allocator(self)

    def pop_back(self):
        return _pyocr.StringVector_pop_back(self)

    def erase(self, *args):
        return _pyocr.StringVector_erase(self, *args)

    def __init__(self, *args):
        this = _pyocr.new_StringVector(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _pyocr.StringVector_push_back(self, x)

    def front(self):
        return _pyocr.StringVector_front(self)

    def back(self):
        return _pyocr.StringVector_back(self)

    def assign(self, n, x):
        return _pyocr.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _pyocr.StringVector_resize(self, *args)

    def insert(self, *args):
        return _pyocr.StringVector_insert(self, *args)

    def reserve(self, n):
        return _pyocr.StringVector_reserve(self, n)

    def capacity(self):
        return _pyocr.StringVector_capacity(self)
    __swig_destroy__ = _pyocr.delete_StringVector
    __del__ = lambda self: None
StringVector_swigregister = _pyocr.StringVector_swigregister
StringVector_swigregister(StringVector)

class FloatVVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FloatVVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FloatVVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pyocr.FloatVVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyocr.FloatVVector___nonzero__(self)

    def __bool__(self):
        return _pyocr.FloatVVector___bool__(self)

    def __len__(self):
        return _pyocr.FloatVVector___len__(self)

    def __getslice__(self, i, j):
        return _pyocr.FloatVVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyocr.FloatVVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyocr.FloatVVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyocr.FloatVVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyocr.FloatVVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyocr.FloatVVector___setitem__(self, *args)

    def pop(self):
        return _pyocr.FloatVVector_pop(self)

    def append(self, x):
        return _pyocr.FloatVVector_append(self, x)

    def empty(self):
        return _pyocr.FloatVVector_empty(self)

    def size(self):
        return _pyocr.FloatVVector_size(self)

    def swap(self, v):
        return _pyocr.FloatVVector_swap(self, v)

    def begin(self):
        return _pyocr.FloatVVector_begin(self)

    def end(self):
        return _pyocr.FloatVVector_end(self)

    def rbegin(self):
        return _pyocr.FloatVVector_rbegin(self)

    def rend(self):
        return _pyocr.FloatVVector_rend(self)

    def clear(self):
        return _pyocr.FloatVVector_clear(self)

    def get_allocator(self):
        return _pyocr.FloatVVector_get_allocator(self)

    def pop_back(self):
        return _pyocr.FloatVVector_pop_back(self)

    def erase(self, *args):
        return _pyocr.FloatVVector_erase(self, *args)

    def __init__(self, *args):
        this = _pyocr.new_FloatVVector(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _pyocr.FloatVVector_push_back(self, x)

    def front(self):
        return _pyocr.FloatVVector_front(self)

    def back(self):
        return _pyocr.FloatVVector_back(self)

    def assign(self, n, x):
        return _pyocr.FloatVVector_assign(self, n, x)

    def resize(self, *args):
        return _pyocr.FloatVVector_resize(self, *args)

    def insert(self, *args):
        return _pyocr.FloatVVector_insert(self, *args)

    def reserve(self, n):
        return _pyocr.FloatVVector_reserve(self, n)

    def capacity(self):
        return _pyocr.FloatVVector_capacity(self)
    __swig_destroy__ = _pyocr.delete_FloatVVector
    __del__ = lambda self: None
FloatVVector_swigregister = _pyocr.FloatVVector_swigregister
FloatVVector_swigregister(FloatVVector)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pyocr.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyocr.IntVector___nonzero__(self)

    def __bool__(self):
        return _pyocr.IntVector___bool__(self)

    def __len__(self):
        return _pyocr.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _pyocr.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyocr.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyocr.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyocr.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyocr.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyocr.IntVector___setitem__(self, *args)

    def pop(self):
        return _pyocr.IntVector_pop(self)

    def append(self, x):
        return _pyocr.IntVector_append(self, x)

    def empty(self):
        return _pyocr.IntVector_empty(self)

    def size(self):
        return _pyocr.IntVector_size(self)

    def swap(self, v):
        return _pyocr.IntVector_swap(self, v)

    def begin(self):
        return _pyocr.IntVector_begin(self)

    def end(self):
        return _pyocr.IntVector_end(self)

    def rbegin(self):
        return _pyocr.IntVector_rbegin(self)

    def rend(self):
        return _pyocr.IntVector_rend(self)

    def clear(self):
        return _pyocr.IntVector_clear(self)

    def get_allocator(self):
        return _pyocr.IntVector_get_allocator(self)

    def pop_back(self):
        return _pyocr.IntVector_pop_back(self)

    def erase(self, *args):
        return _pyocr.IntVector_erase(self, *args)

    def __init__(self, *args):
        this = _pyocr.new_IntVector(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _pyocr.IntVector_push_back(self, x)

    def front(self):
        return _pyocr.IntVector_front(self)

    def back(self):
        return _pyocr.IntVector_back(self)

    def assign(self, n, x):
        return _pyocr.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _pyocr.IntVector_resize(self, *args)

    def insert(self, *args):
        return _pyocr.IntVector_insert(self, *args)

    def reserve(self, n):
        return _pyocr.IntVector_reserve(self, n)

    def capacity(self):
        return _pyocr.IntVector_capacity(self)
    __swig_destroy__ = _pyocr.delete_IntVector
    __del__ = lambda self: None
IntVector_swigregister = _pyocr.IntVector_swigregister
IntVector_swigregister(IntVector)

class IntVVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pyocr.IntVVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyocr.IntVVector___nonzero__(self)

    def __bool__(self):
        return _pyocr.IntVVector___bool__(self)

    def __len__(self):
        return _pyocr.IntVVector___len__(self)

    def __getslice__(self, i, j):
        return _pyocr.IntVVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyocr.IntVVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyocr.IntVVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyocr.IntVVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyocr.IntVVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyocr.IntVVector___setitem__(self, *args)

    def pop(self):
        return _pyocr.IntVVector_pop(self)

    def append(self, x):
        return _pyocr.IntVVector_append(self, x)

    def empty(self):
        return _pyocr.IntVVector_empty(self)

    def size(self):
        return _pyocr.IntVVector_size(self)

    def swap(self, v):
        return _pyocr.IntVVector_swap(self, v)

    def begin(self):
        return _pyocr.IntVVector_begin(self)

    def end(self):
        return _pyocr.IntVVector_end(self)

    def rbegin(self):
        return _pyocr.IntVVector_rbegin(self)

    def rend(self):
        return _pyocr.IntVVector_rend(self)

    def clear(self):
        return _pyocr.IntVVector_clear(self)

    def get_allocator(self):
        return _pyocr.IntVVector_get_allocator(self)

    def pop_back(self):
        return _pyocr.IntVVector_pop_back(self)

    def erase(self, *args):
        return _pyocr.IntVVector_erase(self, *args)

    def __init__(self, *args):
        this = _pyocr.new_IntVVector(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _pyocr.IntVVector_push_back(self, x)

    def front(self):
        return _pyocr.IntVVector_front(self)

    def back(self):
        return _pyocr.IntVVector_back(self)

    def assign(self, n, x):
        return _pyocr.IntVVector_assign(self, n, x)

    def resize(self, *args):
        return _pyocr.IntVVector_resize(self, *args)

    def insert(self, *args):
        return _pyocr.IntVVector_insert(self, *args)

    def reserve(self, n):
        return _pyocr.IntVVector_reserve(self, n)

    def capacity(self):
        return _pyocr.IntVVector_capacity(self)
    __swig_destroy__ = _pyocr.delete_IntVVector
    __del__ = lambda self: None
IntVVector_swigregister = _pyocr.IntVVector_swigregister
IntVVector_swigregister(IntVVector)

class NetAPI(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, NetAPI, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, NetAPI, name)
    __repr__ = _swig_repr

    def __init__(self, weights_f, lookup_f):
        this = _pyocr.new_NetAPI(weights_f, lookup_f)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def load_weights_file(self):
        return _pyocr.NetAPI_load_weights_file(self)

    def initialize_dimensions(self):
        return _pyocr.NetAPI_initialize_dimensions(self)

    def generateSequences(self, arg2, arg3):
        return _pyocr.NetAPI_generateSequences(self, arg2, arg3)

    def test(self, arg2):
        return _pyocr.NetAPI_test(self, arg2)

    def train(self, arg2, arg3):
        return _pyocr.NetAPI_train(self, arg2, arg3)

    def train2(self, arg2, arg3, arg4):
        return _pyocr.NetAPI_train2(self, arg2, arg3, arg4)

    def exportModel(self):
        return _pyocr.NetAPI_exportModel(self)
    __swig_destroy__ = _pyocr.delete_NetAPI
    __del__ = lambda self: None
NetAPI_swigregister = _pyocr.NetAPI_swigregister
NetAPI_swigregister(NetAPI)

# This file is compatible with both classic and new-style classes.


